'use client';
import {useEffect,useMemo,useState} from 'react';
import {mapsUrl,recommend,routePlans,tripCost,validPoint,type Point,type RouteMatrix,type TravelSettings,type Vehicle} from '../lib/travel';
import type {BasketItem,Comparison,Shop} from '../lib/types';
import type {Area} from '../lib/location';
const ft=(n:number)=>new Intl.NumberFormat('hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(n);
const vehicles:Record<Vehicle,string>={petrol:'Benzines autó',diesel:'Dízelautó',hybrid:'Hibrid autó',electric:'Elektromos autó',bicycle:'Kerékpár',walking:'Gyalog'};
export function TravelPlanner({basket,shops,comparison,loyalty,area,settings,onChange,unresolved}:{basket:BasketItem[];shops:Shop[];comparison:Comparison|null;loyalty:string[];area:Area;settings:TravelSettings;onChange:(s:TravelSettings)=>void;unresolved:number}){
 const [configured,setConfigured]=useState<boolean|null>(null),[location,setLocation]=useState<Point|null>(null),[geoError,setGeoError]=useState(''),[locating,setLocating]=useState(false);
 const [routing,setRouting]=useState<{key:string;matrix:RouteMatrix}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[manualKm,setManualKm]=useState(20),[manualStops,setManualStops]=useState(1);
 const origin=location||area.place,routeKey=JSON.stringify({origin,vehicle:settings.vehicle,shops:shops.map(s=>s.id)});
 useEffect(()=>{let gone=false;fetch('/api/routes',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(!gone)setConfigured(d.configured===true);}).catch(()=>{if(!gone)setConfigured(false);});return()=>{gone=true;};},[]);
 useEffect(()=>{setLocation(null);},[area.place?.id]);
 useEffect(()=>{
  setRouting(null);setError('');setBusy(false);
  if(!configured||!origin||!shops.length||shops.length>8||!basket.length)return;
  const controller=new AbortController();setBusy(true);
  const timer=setTimeout(()=>{fetch('/api/routes',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({origin,vehicle:settings.vehicle,shopIds:shops.map(s=>s.id)})}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error?.message||'Az útvonal nem számolható.');return d;}).then(d=>{if(!controller.signal.aborted)setRouting({key:routeKey,matrix:d.matrix});}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});},400);
  return()=>{clearTimeout(timer);controller.abort();};
 },[configured,routeKey,retry,basket.length]);
 const plans=useMemo(()=>comparison&&routing?.key===routeKey?routePlans(basket,shops,comparison.quotes,loyalty,routing.matrix,settings):[],[basket,shops,comparison,loyalty,routing,routeKey,settings]);
 const best=recommend(plans,settings.minimumSaving),single=plans.find(p=>p.shopIds.length===1),multi=plans.find(p=>p.shopIds.length>1);
 const shown=[...new Map([best,single,multi].filter(p=>!!p).map(p=>[p!.id,p!])).values()];
 const powered=!['bicycle','walking'].includes(settings.vehicle),cost=tripCost(manualKm,manualStops,settings);
 const setNumber=(key:keyof TravelSettings,value:string,max:number)=>onChange({...settings,[key]:Math.max(0,Math.min(max,Number(value)||0))});
 const label=(id:string)=>{const s=shops.find(s=>s.id===id);return `${s?.name||id}, ${s?.city||''} ${s?.address||''}`;};
 function locate(){if(!navigator.geolocation){setGeoError('A helymeghatározás nem elérhető.');return;}setLocating(true);setGeoError('');navigator.geolocation.getCurrentPosition(p=>{const point={latitude:p.coords.latitude,longitude:p.coords.longitude};if(validPoint(point))setLocation(point);else setGeoError('Jelenleg magyarországi kiindulóponttal számolunk.');setLocating(false);},()=>{setGeoError('A helymeghatározás nem sikerült. Használhatod a település központját.');setLocating(false);},{timeout:10000,maximumAge:60000});}
 return <section className="card travel-section" id="travel"><div className="section-title"><span className="step">4</span><h2>A kosár ára + az odavezető út</h2></div>
  <p>A teljes oda-vissza út költségével döntünk. A kicsit drágább, közeli bolt összességében kedvezőbb lehet.</p>
  <div className="travel-fields"><label>Mivel indulsz?<select value={settings.vehicle} onChange={e=>onChange({...settings,vehicle:e.target.value as Vehicle,consumption:e.target.value==='electric'?17:['walking','bicycle'].includes(e.target.value)?0:7,energyPrice:e.target.value==='electric'?70:650})}>{Object.entries(vehicles).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
  {powered&&<><label>Fogyasztás ({settings.vehicle==='electric'?'kWh':'liter'} / 100 km)<input type="number" min="0" max="100" step="0.1" value={settings.consumption} onChange={e=>setNumber('consumption',e.target.value,100)}/></label><label>{settings.vehicle==='electric'?'Áramár (Ft / kWh)':'Üzemanyagár (Ft / liter)'}<input type="number" min="0" max="10000" value={settings.energyPrice} onChange={e=>setNumber('energyPrice',e.target.value,10000)}/></label></>}
  <label>Egyéb járműköltség (Ft / km)<input type="number" min="0" max="10000" value={settings.wearPerKm} onChange={e=>setNumber('wearPerKm',e.target.value,10000)}/></label>
  {powered&&<label>Parkolás üzletenként (Ft)<input type="number" min="0" max="100000" value={settings.parkingPerStop} onChange={e=>setNumber('parkingPerStop',e.target.value,100000)}/></label>}
  <label>Legfeljebb ennyi üzlet<select value={settings.maxStops} onChange={e=>onChange({...settings,maxStops:Number(e.target.value)})}><option value={1}>1 üzlet</option><option value={2}>2 üzlet</option><option value={3}>3 üzlet</option></select></label>
  <label>Több boltért legalább ennyit spórolnék (Ft)<input type="number" min="0" max="100000" step="100" value={settings.minimumSaving} onChange={e=>setNumber('minimumSaving',e.target.value,100000)}/></label></div>
  <p className="hint">A kezdő fogyasztás és energiaár példaérték: írd át a sajátodra. Az időt külön mutatjuk; útdíjat és forgalmi késést nem számítunk. Kerékpárnál és gyalog nincs üzemanyagköltség.</p>
  <div className="route-origin"><strong>Indulás és visszaérkezés: {location?'Jelenlegi helyed':area.place?`${area.place.name} központja`:'Válassz települést'}</strong><button onClick={locate} disabled={locating}>{locating?'Helymeghatározás…':'Jelenlegi helyem használata'}</button>{location&&<button onClick={()=>setLocation(null)}>Településközpont használata</button>}</div>
  <p className="hint">A pontos helyedet nem mentjük el. Útvonaltervezéskor az openrouteservice kapja meg; a térképlink megnyitásakor a Google Maps is. A boltok körzetét továbbra is a választott település alapján szűrjük.</p>
  {geoError&&<p className="warning" role="alert">{geoError}</p>}
  {configured===false&&<p className="warning">Az automatikus közúti útvonaltervezés még nincs bekapcsolva. Addig a lenti kalkulátorral számolhatsz; légvonalbeli távolságból nem ajánlunk bevásárlási útvonalat.</p>}
  {shops.length>8&&<p className="warning">Az útvonalak összehasonlításához jelölj ki legfeljebb 8 üzletet, például a kedvenceidet. Az árlistában minden kijelölt üzlet továbbra is szerepel.</p>}
  {busy&&<p role="status">Oda-vissza útvonalak lekérése…</p>}{error&&<p className="error" role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>Újrapróbálom</button></p>}
  {unresolved>0&&<p className="hint">A teljes útiköltséges ajánláshoz válaszd ki a lista minden termékét.</p>}
  {!unresolved&&best&&origin&&<><p className="result-summary"><b>{best.shopIds.length===1?'Elég egy üzletbe menned.':`${best.shopIds.length} üzlettel jársz jobban.`}</b> {single&&best!==single?`A termékekkel és az úttal együtt ${ft(single.total-best.total)} a megtakarítás.`:multi&&best===single?multi.total>=single!.total?`A többüzletes változat ${ft(multi.total-single!.total)}-tal drágább.`:'A többüzletes megtakarítás nem éri el a megadott határodat.':''}</p>
  <div className="plans">{shown.map(p=><article className={'plan '+(p.id===best.id?'best':'')} key={p.id}><div className="eyebrow">{p.shopIds.length} ÜZLET {p.id===best.id&&<span className="badge">Ajánlott</span>}</div><h3>{p.route.map(id=>shops.find(s=>s.id===id)?.name).join(' + ')}</h3><div className="plan-total">{ft(p.total)}</div><dl><div><dt>Termékek és visszaváltási díj</dt><dd>{ft(p.subtotal+p.deposits)}</dd></div><div><dt>Energia / üzemanyag</dt><dd>{ft(p.energyCost)}</dd></div><div><dt>Egyéb járműköltség + parkolás</dt><dd>{ft(p.wearCost+p.parkingCost)}</dd></div><div><dt>Teljes oda-vissza út</dt><dd>{p.distanceKm.toLocaleString('hu-HU',{maximumFractionDigits:1})} km · ~{Math.round(p.minutes)} perc</dd></div></dl><ol className="route-stops"><li>Kiindulópont</li>{p.route.map(id=><li key={id}>{label(id)}</li>)}<li>Vissza a kiindulópontra</li></ol><a target="_blank" rel="noreferrer" href={mapsUrl(origin,p.route,shops,settings.vehicle)||undefined}>Útvonal megnyitása a Google Mapsben ↗</a><details><summary>Mit melyik boltban vegyél?</summary>{p.lines.map(l=><p key={l.code}>{l.qty} × {l.name} · {label(l.shopId)} · <b>{ft(l.total)}</b></p>)}</details></article>)}</div><p className="hint">Az ajánlás a kijelölt üzletekre, a friss áradatokra és legfeljebb {settings.maxStops} megállóra vonatkozik. Az út ideje nem tartalmazza a bevásárlást. A Google Maps újraszámolhatja az útvonalat. <a href="https://openrouteservice.org/" target="_blank" rel="noreferrer">© openrouteservice</a> · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap közreműködők</a></p></>}
  {comparison&&routing?.key===routeKey&&!busy&&!unresolved&&!best&&<p className="warning">Nincs teljes kosárhoz ellenőrizhető útvonal a megadott megállószámmal. Hiányzó ár vagy elérhetetlen útvonal nem számít 0 Ft-nak.</p>}
  <details open={configured===false}><summary>Saját útiköltség kiszámítása</summary><div className="travel-fields"><label>Teljes oda-vissza út (km)<input type="number" min="0" max="2000" step="0.1" value={manualKm} onChange={e=>setManualKm(Math.max(0,Math.min(2000,Number(e.target.value)||0)))}/></label><label>Üzletek száma<select value={manualStops} onChange={e=>setManualStops(Number(e.target.value))}>{[1,2,3].map(n=><option key={n}>{n}</option>)}</select></label></div><p className="cost-result">Ennek az útnak a becsült költsége: <strong>{ft(cost.travel)}</strong></p><p className="hint">A fenti járműadatokkal, energiaárral és parkolással számolunk. Ezt a kézzel megadott utat nem adjuk automatikusan az üzletek árához.</p></details>
 </section>;
}
